update for redis-py API change (v3.2.0)
Handle error:

redis.exceptions.DataError: Invalid input of type: 'list'. Convert to a byte, string or number first.