hot-fix: Update return from psutil.disk_partitions function call (#190)
* hot-fix: Update return from psutil.disk_partitions function

Due to psutil 6.0.0 release, it is found that it broke the instance_stats service with the following error:

```
Traceback (most recent call last):
  File "/export/home/hysdsops/mozart/ops/hysds/scripts/log_instance_stats.py", line 119, in <module>
    daemon(args.redis_url, args.redis_key, args.interval)
  File "/export/home/hysdsops/mozart/ops/hysds/scripts/log_instance_stats.py", line 79, in daemon
    for device, mnt_point, fs_type, fs_opts, max_file, max_path, *other in psutil.disk_partitions():
ValueError: not enough values to unpack (expected at least 6, got 4)
```
According to the psutil pull request, https://github.com/giampaolo/psutil/pull/2405, max_file and max_path were removed because if there's a NFS (network filesystem) this function can potentially take a long time to complete.

* bump version

---------

Co-authored-by: Mike Cayanan <michael.d.cayanan@jpl.nasa.gov>